[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true
  

[[redirects]]
  from = "/about"
  to =   "https://kbsum1926.in/"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio"
  to =   "https://kbsum1926.in/"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to =   "https://kbsum1926.in/"
  status = 301
  force = true


[[redirects]]
  from = "/upcomingevents"
  to =   "https://kbsum1926.in/"
  status = 301
  force = true